In [4]:
import os
print(os.getcwd())

C:\Users\efahy

In [1]:
import pandas as pd
import os

print("Current working directory:", os.getcwd())


train_file_path = "wildfires_training.csv"
test_file_path = "wildfires_test.csv"

try:
    # Loading the datasets
    train_df = pd.read_csv(train_file_path)
    test_df = pd.read_csv(test_file_path)
    
    print("Files loaded")
    print("\nTraining set:")
    display(train_df)
    
    print("\nTest set:")
    display(test_df)
    
except FileNotFoundError:
    print("Files not found.")

Current working directory: C:\Users\efahy
✅ Files loaded successfully!

Training set:

,fire,year,temp,humidity,rainfall,drought_code,buildup_index,day,month,wind_speed
0,no,2015,28,59,0.0,8.06,3.47,1,6,19
1,no,2010,30,61,1.3,8.17,4.03,2,6,13
2,no,2009,26,83,13.1,8.08,3.59,3,6,22
3,no,2017,25,87,2.5,7.18,2.42,4,6,15
4,no,2014,28,77,0.0,14.98,4.63,5,6,18
...,...,...,...,...,...,...,...,...,...,...
149,yes,2017,31,67,0.0,45.15,17.89,26,9,15
150,no,2017,29,89,4.4,8.74,6.52,27,9,15
151,no,2009,27,88,0.5,8.87,3.71,28,9,30
152,no,2016,25,56,0.1,15.54,6.10,29,9,20
153,no,2012,24,62,0.2,16.72,5.75,30,9,17

Test set:

,fire,year,temp,humidity,rainfall,drought_code,buildup_index,day,month,wind_speed
0,no,2015,33,68,4.5,9.12,5.09,19,6,16
1,yes,2009,28,56,0.0,38.17,21.21,12,6,18
2,no,2017,30,64,0.6,15.38,6.24,24,9,19
3,no,2007,23,74,8.3,7.36,2.27,14,9,28
4,no,2017,31,72,0.3,30.47,5.63,7,9,17
5,no,2013,30,73,0.1,16.28,3.58,4,9,18
6,yes,2015,34,66,0.0,210.55,62.99,28,8,16
7,yes,2013,36,67,0.0,131.20,34.92,20,8,19
8,no,2012,34,74,0.0,18.95,8.94,11,7,15
9,no,2015,32,70,1.4,10.05,8.31,9,7,16
10,yes,2013,33,54,0.0,80.94,26.02,27,6,18
11,yes,2017,32,55,0.0,18.60,8.44,21,6,16
12,no,2014,33,47,1.1,8.37,7.87,22,6,14
13,no,2007,33,57,0.8,8.52,7.07,23,6,18
14,yes,2015,36,66,0.0,17.01,10.75,24,6,17
15,yes,2010,34,72,0.0,26.04,13.34,25,6,17
16,yes,2016,36,64,0.0,34.92,17.24,26,6,17
17,yes,2007,35,53,0.0,43.33,21.39,27,6,16
18,yes,2013,36,35,0.0,52.77,27.51,28,6,14
19,yes,2010,37,36,0.6,37.44,18.80,29,6,14
20,no,2014,35,42,1.7,8.86,11.55,30,6,16
21,no,2009,27,56,2.2,8.92,4.19,1,7,20
22,yes,2017,34,47,0.0,18.57,7.90,2,7,16
23,yes,2013,35,56,0.1,27.32,10.47,3,7,17
24,yes,2007,34,60,0.0,37.56,14.94,4,7,18
25,yes,2008,33,46,0.0,46.53,19.47,5,7,18
26,yes,2010,35,40,0.3,45.97,17.40,6,7,16
27,no,2008,33,61,1.1,57.35,22.04,24,7,19
28,no,2011,39,65,1.2,16.39,11.74,25,7,9
29,no,2015,36,56,0.2,20.61,10.77,26,7,12
30,no,2007,30,86,0.0,28.64,12.22,27,7,18
31,yes,2012,34,55,0.0,37.76,15.73,28,7,17
32,yes,2012,35,57,0.0,48.17,19.91,29,7,16
33,yes,2014,36,57,0.0,58.10,24.42,30,7,18
34,yes,2009,36,53,0.0,67.29,28.65,31,7,15
35,no,2017,38,54,0.0,11.50,5.07,1,8,14
36,yes,2008,33,38,0.0,167.94,64.13,26,8,18
37,yes,2015,36,54,0.0,177.81,68.27,27,8,14
38,no,2009,34,57,0.4,166.58,30.69,28,8,14
39,yes,2014,34,52,0.5,149.21,31.05,29,8,18
40,yes,2013,35,47,0.0,159.81,36.57,30,8,17
41,yes,2007,31,60,0.0,168.73,39.65,31,8,20
42,no,2011,30,85,0.0,8.63,1.44,1,9,17
43,no,2008,27,69,0.0,17.24,4.56,2,9,21
44,yes,2009,29,76,0.0,25.00,6.44,3,9,17
45,no,2012,29,64,0.2,27.59,6.10,4,9,15
46,no,2007,29,59,4.1,8.67,4.42,5,9,13
47,no,2011,35,70,6.5,9.45,3.84,6,9,16
48,yes,2012,32,60,0.0,18.53,6.88,7,9,16
49,yes,2012,31,87,0.0,26.95,8.61,8,9,14